//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int custid { get; set; }
        public string custname { get; set; }
        public Nullable<int> age { get; set; }
        public string caddress { get; set; }
    }

}
